import crypto from 'crypto';

const JWT_SECRET = process.env.JWT_SECRET || 'fallback-jwt-secret-key';

/**
 * Signs a URL path so the worker can verify it was generated by the trusted Next.js server.
 * @param basePath The base URL path to sign (e.g. '/api/raw/123')
 * @param clientIp The IP address of the client requesting the stream
 * @param expiresInHours How long the URL should be valid for (default 12 hours)
 * @returns The base path appended with ?expires=...&signature=...
 */
export function signWorkerUrl(basePath: string, clientIp: string, expiresInHours: number = 12): string {
  // 1. Calculate expiration timestamp (in milliseconds)
  const expires = Date.now() + expiresInHours * 60 * 60 * 1000;

  // 2. Generate HMAC signature of the path, expiration time, AND client IP
  // Format: "path|expires|ip"
  const payload = `${basePath}|${expires}|${clientIp}`;
  
  const signature = crypto
    .createHmac('sha256', JWT_SECRET)
    .update(payload)
    .digest('hex');

  // 3. Append to URL
  const separator = basePath.includes('?') ? '&' : '?';
  return `${basePath}${separator}expires=${expires}&signature=${signature}`;
}
